component_depth: 3
languages:
- php
- name: php
  production:
      exclude:
          - /api/src/Resolver/.*
          - /api/src/Resolver/StudentMutationResolver.php
  test:
    include:
        - /api/tests/.*
        - /api/src/Service/.*
    exclude:
        - /api/src/Resolver/StudentMutationResolver.php
exclude:
- /nlx-setup/.*
- /resources/.*
- /api/bin/.*
- /api/config/.*
- /api/docker/.*
- /api/docs/.*
- /api/helm/.*
- /api/migrations/.*
- /api/nlx-setup/.*
- /api/public/.*
- /api/templates/.*
- /api/translations/.*
- /api/var/.*
- /api/vendor/.*
- /api/src/Entity/.*

