parameters:
    # Adds a fallback API KEYS if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet. 
    # You should not need to change this value.

    # Security Details
    env(APP_COMMONGROUND_ID): ""
    env(APP_COMMONGROUND_KEY): ""
    env(APP_COMMONGROUND_SECRET): ""

    common_ground.app.id: "%env(APP_COMMONGROUND_ID)%"
    app_commonground_id: "%env(APP_COMMONGROUND_ID)%"
    app_commonground_key: "%env(APP_COMMONGROUND_KEY)%"
    app_commonground_secret: "%env(APP_COMMONGROUND_SECRET)%"

    # Application Parameters
    env(APP_ENV): "prod"
    env(APP_DEBUG):
    env(APP_CACHE):
    env(APP_AUTH):
    env(AUDITTRAIL_ENABLED): ""
    env(NOTIFICATION_ENABLED):
    env(HEALTH_ENABLED):
    env(APP_VERSION): "1.0.0"
    env(APP_MAJOR_VERSION): "v1"
    env(APP_NAME): "Proto Component"
    env(APP_ID): ""
    env(APP_DESCRIPTION): "A commonground component"
    env(APP_DOMAIN): "zaakonline.nl"
    env(APP_TITLE): "Proto Component"
    env(APP_LOGO): "zaakonline.nl"
    env(APP_HOME): "zaakonline.nl"
    env(APP_SUBDOMAIN):
    env(APP_SUBPATH):
    env(APP_SUBPATH_ROUTING):
    env(APP_DEMO): "pc.zaakonline.nl"
    env(APP_WEB):
    env(APP_INTERNAL):
    env(APP_BUILD_ALL_FIXTURES):
    env(APP_URL): "http://localhost"

    env(APP_CONTAINER): ""
    env(APP_REPRO): ""
  
    app_env: "%env(APP_ENV)%"
    app_debug: "%env(APP_DEBUG)%"
    app_cache: "%env(APP_CACHE)%"
    app_auth: "%env(APP_AUTH)%"
    app_audittrail: "%env(AUDITTRAIL_ENABLED)%"
    app_notification: "%env(NOTIFICATION_ENABLED)%"
    app_health: "%env(HEALTH_ENABLED)%"
    app_version: "%env(APP_VERSION)%"
    app_major_version: "%env(APP_MAJOR_VERSION)%"
    app_name: "%env(APP_NAME)%"
    app_id: "%env(APP_ID)%"
    app_description: "%env(APP_DESCRIPTION)%"
    app_domain: "%env(APP_DOMAIN)%"
    app_type: "%env(APP_TYPE)%"
    app_title: "%env(APP_TITLE)%"
    app_logo: "%env(APP_LOGO)%"
    app_home: "%env(APP_HOME)%"
    app_subdomain: "%env(APP_SUBDOMAIN)%"
    app_subpath: "%env(APP_SUBPATH)%"
    app_subpath_routing: "%env(APP_SUBPATH_ROUTING)%"
    app_url: "%env(APP_URL)%"
    app_demo: "%env(APP_DEMO)%"
    app_container: "%env(APP_CONTAINER)%"
    app_repro: "%env(APP_REPRO)%"
    app_web: "%env(APP_WEB)%"
    app_internal: "%env(APP_INTERNAL)%"
    app_build_all_fixtures: "%env(APP_BUILD_ALL_FIXTURES)%"

    # Organisatie details
    env(GOOGLE_TAG_MANAGER_ID): ""
    env(HUBSPOT_EMBED_CODE): ""

    env(CONTAINER_REGISTRY_BASE): ""
    env(CONTAINER_PROJECT_NAME): ""

    env(ORGANIZATION_NAME): ""
    env(ORGANIZATION_EMAIL_ADDRESS): ""
    env(ORGANIZATION_COUNTRY_NAME): ""
    env(ORGANIZATION_STATE): ""
    env(ORGANIZATION_LOCALITY): ""
    env(ORGANIZATION_UNIT_NAME): ""

    google_tag_manager_id: "%env(GOOGLE_TAG_MANAGER_ID)%"
    hubspot_embed_code: "%env(HUBSPOT_EMBED_CODE)%"

    container_registry_base: "%env(CONTAINER_REGISTRY_BASE)%"
    container_project_name: "%env(CONTAINER_PROJECT_NAME)%"

    organization_name: "%env(ORGANIZATION_NAME)%"
    organization_email: "%env(ORGANIZATION_EMAIL_ADDRESS)%"
    organization_country: "%env(ORGANIZATION_COUNTRY_NAME)%"
    organization_state: "%env(ORGANIZATION_STATE)%"
    organization_locality: "%env(ORGANIZATION_LOCALITY)%"
    organization_unit: "%env(ORGANIZATION_UNIT_NAME)%"

    # Dit is hieronder nu anders geregeld (ofwel aanpassen)
    env(APP_APPLICATION_KEY): ""
    env(APP_USER_KEY): ""
    env(AUTH_PROVIDER_USER): ""
    env(AUTH_PROVIDER_APPLICATION): ""

    env(TRUSTED_HOSTS): ""
    env(TRUSTED_PROXIES): ""

    env(NLX_OUTWAY): ""
    env(NLX_INWAY): ""

    # Dit is hieronder nu anders geregeld (ofwel aanpassen)
    auth_provider_user: "%env(AUTH_PROVIDER_USER)%"
    auth_provider_application: "%env(AUTH_PROVIDER_APPLICATION)%"
    app_application_key: "%env(APP_APPLICATION_KEY)%"
    app_user_key: "%env(APP_USER_KEY)%"

    trusted_hosts: "%env(TRUSTED_HOSTS)%"
    trusted_proxies: "%env(TRUSTED_PROXIES)%"

    nlx_outway: "%env(NLX_OUTWAY)%"
    nlx_inway: "%env(NLX_INWAY)%"

    # Busnes Engine
    env(APP_COMMONGROUND_BE_LOCATION): "https://ac.%env(APP_DOMAIN)%"
    env(APP_COMMONGROUND_BE_USERNAME): "%env(APP_COMMONGROUND_ID)%"
    env(APP_COMMONGROUND_BE_PASSWORD): "%env(APP_COMMONGROUND_SECRET)%"

    # Autorisatiecomponent
    env(APP_COMMONGROUND_AC_LOCATION): "https://ac.%env(APP_DOMAIN)%"
    env(APP_COMMONGROUND_AC_ID): "%env(APP_COMMONGROUND_ID)%"
    env(APP_COMMONGROUND_AC_SECRET): "%env(APP_COMMONGROUND_SECRET)%"

    # Notificatierouteringcomponent
    env(APP_COMMONGROUND_NRC_LOCATION): "https://nrc.%env(APP_DOMAIN)%"
    env(APP_COMMONGROUND_NRC_ID): "%env(APP_COMMONGROUND_ID)%"
    env(APP_COMMONGROUND_NRC_SECRET): "%env(APP_COMMONGROUND_SECRET)%"

    # Zaakregistratiecomponent
    env(APP_COMMONGROUND_ZRC_LOCATION): "https://zrc.%env(APP_DOMAIN)%"
    env(APP_COMMONGROUND_ZRC_ID): "%env(APP_COMMONGROUND_ID)%"
    env(APP_COMMONGROUND_ZRC_SECRET): "%env(APP_COMMONGROUND_SECRET)%"

    # Zaaktypecatalogus
    env(APP_COMMONGROUND_ZTC_LOCATION): "https://ztc.%env(APP_DOMAIN)%"
    env(APP_COMMONGROUND_ZTC_ID): "%env(APP_COMMONGROUND_ID)%"
    env(APP_COMMONGROUND_ZTC_SECRET): "%env(APP_COMMONGROUND_SECRET)%"

    # Documentregistratiecomponent
    env(APP_COMMONGROUND_DRC_LOCATION): "https://drc.%env(APP_DOMAIN)%"
    env(APP_COMMONGROUND_DRC_ID): "%env(APP_COMMONGROUND_ID)%"
    env(APP_COMMONGROUND_DRC_SECRET): "%env(APP_COMMONGROUND_SECRET)%"

    # Klantinteractiescomponent
    env(APP_COMMONGROUND_KIC_LOCATION): "https://kic.%env(APP_DOMAIN)%"
    env(APP_COMMONGROUND_KIC_ID): "%env(APP_COMMONGROUND_ID)%"
    env(APP_COMMONGROUND_KIC_SECRET): "%env(APP_COMMONGROUND_SECRET)%"
    
    # BasisAdressenGemeenten
    env(APP_COMMONGROUND_BAG_LOCATION): "https://bag.basisregistraties.overheid.nl/api/v1/"
    env(APP_COMMONGROUND_BAG_APIKEY): "%env(APP_COMMONGROUND_KEY)%"
    # KamerVanKoophandel
    env(APP_COMMONGROUND_KVK_LOCATION): "https://kvk.%env(APP_DOMAIN)%"
    env(APP_COMMONGROUND_KVK_APIKEY): "%env(APP_COMMONGROUND_KEY)%"
    common_ground.kvk.location: "%env(APP_COMMONGROUND_KVK_LOCATION)%"
    common_ground.kvk.apikey: "%env(APP_COMMONGROUND_KVK_APIKEY)%"
    # DienstWegverkeer
    env(APP_COMMONGROUND_RDW_LOCATION): "https://rdw.%env(APP_DOMAIN)%"
    env(APP_COMMONGROUND_RDW_APIKEY): "%env(APP_COMMONGROUND_KEY)%"
    # DocumentManagmentService
    env(APP_COMMONGROUND_DMS_LOCATION): "https://dms.%env(APP_DOMAIN)%"
    env(APP_COMMONGROUND_DMS_APIKEY): "%env(APP_COMMONGROUND_KEY)%"
    #n nlx-in
    env(APP_COMMONGROUND_NLX_IN_LOCATION): "https://nlx-in.%env(APP_DOMAIN)%"
    env(APP_COMMONGROUND_NLX_IN_APIKEY): "%env(APP_COMMONGROUND_KEY)%"
    # nlx-out
    env(APP_COMMONGROUND_NLX_OUT_LOCATION): "https://nlx-out.%env(APP_DOMAIN)%"
    env(APP_COMMONGROUND_NLX_OUT_APIKEY): "%env(APP_COMMONGROUND_KEY)%"
    # ProcesTypeCatalogus
    env(APP_COMMONGROUND_PTC_LOCATION): "https://ptc.%env(APP_ENV)%"
    env(APP_COMMONGROUND_PTC_APIKEY): "%env(APP_COMMONGROUND_KEY)%"
    # StufService
    env(APP_COMMONGROUND_STUF_LOCATION): "https://stuf.%env(APP_DOMAIN)%"
    env(APP_COMMONGROUND_STUF_APIKEY): "%env(APP_COMMONGROUND_KEY)%"

    # Test for commonground component by array
    common_ground.components:
        be:
            location: "%env(APP_COMMONGROUND_BE_LOCATION)%"
            auth: "username-password"
            username: "%env(APP_COMMONGROUND_BE_USERNAME)%"
            password: "%env(APP_COMMONGROUND_BE_PASSWORD)%"
            accept: "application/ld+json"
            autowire: false
        drc:
            location: "%env(APP_COMMONGROUND_DRC_LOCATION)%"
            auth: "jwt"
            id: "%env(APP_COMMONGROUND_DRC_ID)%"
            secret: "%env(APP_COMMONGROUND_DRC_SECRET)%"
            accept: "application/json"
            autowire: false
        ac:
            location: "%env(APP_COMMONGROUND_AC_LOCATION)%"
            auth: "jwt"
            id: "%env(APP_COMMONGROUND_AC_ID)%"
            secret: "%env(APP_COMMONGROUND_AC_SECRET)%"
            accept: "application/json"
            autowire: false
        nrc:
            location: "%env(APP_COMMONGROUND_NRC_LOCATION)%"
            auth: "jwt"
            id: "%env(APP_COMMONGROUND_NRC_ID)%"
            secret: "%env(APP_COMMONGROUND_NRC_SECRET)%"
            accept: "application/json"
            autowire: false
        zrc:
            location: "%env(APP_COMMONGROUND_ZRC_LOCATION)%"
            auth: "jwt"
            id: "%env(APP_COMMONGROUND_ZRC_ID)%"
            secret: "%env(APP_COMMONGROUND_ZRC_SECRET)%"
            accept: "application/json"
            autowire: false
        ztc:
            location: "%env(APP_COMMONGROUND_ZTC_LOCATION)%"
            auth: "jwt"
            id: "%env(APP_COMMONGROUND_ZTC_ID)%"
            secret: "%env(APP_COMMONGROUND_ZTC_SECRET)%"
            accept: "application/json"
            autowire: false
        kic:
            location: "%env(APP_COMMONGROUND_KIC_LOCATION)%"
            auth: "jwt"
            id: "huwelijksplanner-Wex83XXe"
            secret: "%env(APP_COMMONGROUND_KIC_SECRET)%"
            accept: "application/json"
            autowire: false
        nlx_in:
            location: "%env(APP_COMMONGROUND_NLX_IN_LOCATION)%"
            apikey: "%env(APP_COMMONGROUND_NLX_IN_APIKEY)%"
        nlx_out:
            location: "%env(APP_COMMONGROUND_NLX_OUT_LOCATION)%"
            apikey: "%env(APP_COMMONGROUND_NLX_OUT_APIKEY)%"
        bag:
            location: "%env(APP_COMMONGROUND_BAG_LOCATION)%"
            apikey: "%env(APP_COMMONGROUND_BAG_APIKEY)%"
        kvk:
            location: "%env(APP_COMMONGROUND_KVK_LOCATION)%"
            apikey: "%env(APP_COMMONGROUND_KVK_APIKEY)%"
        rdw:
            location: "%env(APP_COMMONGROUND_RDW_LOCATION)%"
            apikey: "%env(APP_COMMONGROUND_RDW_APIKEY)%"

    common_ground.oas.type: service
    common_ground.oas.host: irc.zaakonline.nl
    common_ground.oas.servers:
        - description: Demo Omgeving
          url: "http://proto.demo.common-ground.dev"
    common_ground.oas.externalDocs:
        - description: OAS Documentatie
          url: "http://proto.demo.common-ground.dev"
    common_ground.oas.developers:
        - name: Conduction
          url: https://github.com/ConductionNL
          email: info@conduction.nl
        - name: Gemeente "s-Hertogenbosch
          url: https://github.com/gemeenteshertogenbosch
          email: info@s-hertogenbosch.nl/
        - name: Gemeente Utrecht
          url: https://github.com/GemeenteUtrecht
          email: info@utrecht.nl
    common_ground.oas.builds:
        - name: travis
          logo: https://travis-ci.org/api-platform/core.svg?branch=master
          url: https://travis-ci.org/api-platform/core
        - name: appveyor
          logo: https://ci.appveyor.com/api/projects/status/grwuyprts3wdqx5l?svg=true
          url: https://ci.appveyor.com/project/dunglas/dunglasapibundle
        - name: codecov
          logo: https://codecov.io/gh/api-platform/core/branch/master/graph/badge.svg
          url: https://codecov.io/gh/api-platform/core
        - name: SensioLabsInsight
          logo: https://insight.sensiolabs.com/projects/92d78899-946c-4282-89a3-ac92344f9a93/mini.png
          url: https://insight.sensiolabs.com/projects/92d78899-946c-4282-89a3-ac92344f9a93
        - name: Scrutinizer Code Quality
          logo: https://scrutinizer-ci.com/g/api-platform/core/badges/quality-score.png?b=master
          url: https://scrutinizer-ci.com/g/api-platform/core/?branch=master

twig:
    globals:
        # Application Parameters
        app_env: "%env(APP_ENV)%"
        app_debug: "%env(APP_DEBUG)%"
        app_cache: "%env(APP_CACHE)%"
        app_auth: "%env(AUTH_ENABLED)%"
        app_audittrail: "%env(AUDITTRAIL_ENABLED)%"
        app_notification: "%env(NOTIFICATION_ENABLED)%"
        app_health: "%env(HEALTH_ENABLED)%"
        app_version: "%env(APP_VERSION)%"
        app_major_version: "%env(APP_MAJOR_VERSION)%"
        app_name: "%env(APP_NAME)%"
        app_id: "%env(APP_ID)%"
        app_description: "%env(APP_DESCRIPTION)%"
        app_domain: "%env(APP_DOMAIN)%"
        app_type: "%env(APP_TYPE)%"
        app_title: "%env(APP_TITLE)%"
        app_logo: "%env(APP_LOGO)%"
        app_home: "%env(APP_HOME)%"
        app_subdomain: "%env(APP_SUBDOMAIN)%"
        app_subpath: "%env(APP_SUBPATH)%"
        app_subpath_routing: "%env(APP_SUBPATH_ROUTING)%"
        app_demo: "%env(APP_DEMO)%"
        app_container: "%env(APP_CONTAINER)%"
        app_repro: "%env(APP_REPRO)%"
        app_web: "%env(APP_WEB)%"
        app_internal: "%env(APP_INTERNAL)%"
        app_build_all_fixtures: "%env(APP_BUILD_ALL_FIXTURES)%"

        # Security Details
        app_commonground_id: "%env(APP_COMMONGROUND_ID)%"
        app_commonground_key: "%env(APP_COMMONGROUND_KEY)%"
        app_commonground_secret: "%env(APP_COMMONGROUND_SECRET)%"

        # Organisations Parameters
        google_tag_manager_id: "%env(GOOGLE_TAG_MANAGER_ID)%"
        hubspot_embed_code: "%env(HUBSPOT_EMBED_CODE)%"

        container_registry_base: "%env(CONTAINER_REGISTRY_BASE)%"
        container_project_name: "%env(CONTAINER_PROJECT_NAME)%"

        organization_name: "%env(ORGANIZATION_NAME)%"
        organization_email: "%env(ORGANIZATION_EMAIL_ADDRESS)%"
        organization_country: "%env(ORGANIZATION_COUNTRY_NAME)%"
        organization_state: "%env(ORGANIZATION_STATE)%"
        organization_locality: "%env(ORGANIZATION_LOCALITY)%"
        organization_unit: "%env(ORGANIZATION_UNIT_NAME)%"

        # Dit is hieronder nu anders geregeld (ofwel aanpassen)
        auth_provider_user: "%env(AUTH_PROVIDER_USER)%"
        auth_provider_application: "%env(AUTH_PROVIDER_APPLICATION)%"
        app_application_key: "%env(APP_APPLICATION_KEY)%"
        app_user_key: "%env(APP_USER_KEY)%"

        trusted_hosts: "%env(TRUSTED_HOSTS)%"
        trusted_proxies: "%env(TRUSTED_PROXIES)%"

        nlx_outway: "%env(NLX_OUTWAY)%"
        nlx_inway: "%env(NLX_INWAY)%"
