# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  version: V1.0
  debug: 0
  cache: true
  internal: false

security:
  applicationKey: "8b55691f-346d-423c-bdcf-3f5365806d39"
  privateKey: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS2dJQkFBS0NBZ0VBdXh2aGsyMHFsRVpzcGxxd0ZQd3QrSTNaTW5neURhSVhXSEZoajRzTEdPQXhpcS9BCnJiQnNzaFpsM3FCR3RnQ2tEcCt1NHlDVE9VWFBMb05jVmQwNlVaYVFKdTJOWTc5TkhDejF2UlBYRE11bmI1RUMKT3ZMZytsdkd5TGlhenltcjNGRFl0WDFmY0JvTFZCVFJWTUtsYmFlK3VDcFhMSDdBYW42SlkyaFU3NWtXZndnRQo3V2FrS0E1djhnNjBrS1BNM0QxaDNoVWNjTnJZeUs3MTRMdzBpMjZhbkZGRHl6TDBSbVNrL21paThSMGtsZUx2Clk1azhoU2hzMXBkUnoxalppT21ZbldCNUFyeTJtVkcyeXVRd1QxQ3IxNUYvRFh2UUdVZ2d6MXNnODNucFJpaGcKTXNzcUpWWWIyeFJVYndkeW9UaHVDRnRBdmNzak5uS1h1OG9BVXZtVFprZ3BGdXZ2aVBOK0E4RmV6Zk5Obk1BUgpOVm1NbkxjdVlHanZlOXVzdjVlZ09melRyZFI5QjBKd2FKY0dmOEc0V09IRGVlb1lZNnFpVnU2dWJBQXJSYVhJClJVQVVKOHEwUUFwUVZNbFZlcDRXQitGUFVFVFdyL0gwUFpzU0dYdjZhdFdWWk04WTRLajQ4NUZ2MTZTSVU5eloKWnRiSUhjV2czbHlCMHRpVUhTSkZQR3ZMbzN1Y05TOVB5QkdUYUV3RDE1NkkzeDgrZmdBZnRnY2pwcUZpbFFqVgphSXBaY1RBWDZ1aDlQWjFiL09DbDVSdnNQMjBBVUt3UnQ0RzdpanNZNlZ3dGk2cXBEemF3ZmthYklSN3NpalZ3ClVjRllVU2FkaVpjU2x0SG52U1NQR1NvTU44OUtZWlV2WXl1dGhWRVExL2tTeFA5aDRxbWl6YkVXSWtNQ0F3RUEKQVFLQ0FnRUFtYXlDanBVQWZadUJyUGVhMndGcnVGSzRhcTB4WHVVY0MzWER6U05EMEFDQ2NBZDlWcW9wKy9KTgpaSlY2dmd5MHNaWVJDMVk3MUxRelAxNkFQYjFmSXBkb2ViQnRpZGthdWVOclNRbThmRFBmcHRBUVp0NElUVmVICllsL01OZzFocTZkeTlVeXRUK0wwSHZDaUpOMWhCVGphZVdPOUNUeHBTSTM0eFA1eGsvL0Y3RHRuNEp1R2c2ZW4KNWNTU0pLR0RwZmQ4SSt4dTJYbkV4cjU4RDBKRVhhaFByOGRHeU9ObW9WSVQrU2R6ZkZpVkxjMmZFOHhOV29nagpLL1JJS3VZc2REaDNNZnFFS08xWmczOExoSVA1OFlxdU9IUzFSeHZEaEtBcTRtTlVJdVNqNVExUVJTZDd6QUozCkNtNGVFcnFwT1NTaHFwZFlDd21HT0RmUnkxaFMvbXJrMm9LQldJanZsQ3hXcWxjeHJyWW83Y09kQzNuZTVTWlgKcTArL050RFgvVUFhMy8xQzNYN1E3ODBqR212VDBHWVcrYWFnaE90YU5TRWtPREhmV2JYQWQxQjNUZGZrdU9tVQpLL2MrMVhYZnJmZG9yaDV3M1pocUhnRVlicHNpM3JDeFNrUmMvMlpzWjA4a25UdFhiYjRqWVcxWWxhR2RzbDIvCnQ0V0JqeWE2VlRsSXdoR2tVQjFQUjJTVFdZb3RLYnl3UHV4RDJRTEtZTkJYRGcrd3R3SDIyays1b2Y1NnBvcmIKK1piNi9oa0NHQUJSMDUvM0RSQ05vSnRIV2tnZjlkaEFtZ1JHWGI5a2pwT1Y3TWdWMkpqMk85MnUxMHA2SGR6TQppbm96NEREcXdVTWdIV3JzRmxzUGZ4ZlVpWmlUZG5PNWlGekFOWUxxU29GdEdKanRUU0VDZ2dFQkFPazI5R00yCjk3Umg4bVJoU05RM2tBQWNZVk42RXg1eWRDMUdrbkltTGwrSEtYUk13a044dFNXeEVxRHh2ekFQSGNac1ZldjAKOE1qYkRwaGVDZnVMN2VYcDRkamZrSlh0dEVYa1NIY1VSVzJhcXNBQkFGeDBBbkk4NzNLQXBTVmIyN29MN2tqSwo1dDVqbXh4R0IwY0RjeXVFOXNMcjcySkFZci9KVW53V25FYjk1WEdaVEVBbVZiUDdwcldjRXZYcjFVRlFSWDlVCk54UWdybjJGdFpITnVxNTlCbGhGb2xGV0EwMlI2WUpjTUZEY0twb1ZUWWFYM25xOEVKai9JcFpkUGJYN0FKa28KTllUSVBEeUIvWkRVOXBpTTgrUjdvN29HZU52eFhmb21mME5HUlZTdXZjRkdSdkdUa29qdVhSUWZib09zcFFFUgpVZng4Z0ppdlBuT0w4Z3NDZ2dFQkFNMWp3TWdPNGJYUkN2cDR2MC9vZXp6Rk5uVE9GSUtRcDlmYWY2d2tZMTlCCk1MTStkdVZSM0J3Z2lOYkpkUzBhV1NlaXpTNDBFZ0FoeXRxSnp4TkUxVmV6OVZuQy80ZG93YWpXMDlkQWh2K2cKdXdDUjczZUxaSFNYODhEQ2dBWnpjcWdXVkFvWkNPVnY2UldXbjJVVk1JbmRBTmxqUXAxR0cwQUwyMmxJb2lpMwp6aHQyNUYrZ3NRelpqelZoMzhEUGRZdWVsRkVYMlAxa3NtWk51TnRqT2MvWVhOekdOcXl5Wm1rZ2puTW1BSzBjCjlQNHloSFNWN0FHUERzVFJCRVZhR3F6bmFiYXVpY2ZzNmdpMFRIVzUxY3ZuTXB4SGE5UFFlQUZxN2hxZmxZWEYKTzVkZUp3VmlINzd6MjE2SkkxTzIxL3FCN0pGeGNhQnYyQ3VSZUdiU3E2a0NnZ0VCQUpOck5KS2V4WGZWemxZYgpsT0RvK25MSGZkSTV3V29tcVQrUmM3TUtaWmZuSlpJcGowYi94clk3dDIzYlFxS0xlNlBaQ1hzdEN5TzhMUDZ0CnV4dXlPVUJ6Vmxzei92NTNFdFIzV0VORm9obUZnbGY2aWhMbkZrREdPZ29rUGNCZXo0ZE1VV1RjTlpId1hyVkIKb3dvRnFVQ2lQU1c3NUVjME1mZlB0LzlPZjV6MGs1djZibFBDcDd3czRCVyt3ZEdJTVBhbldqY0JzZ3RjR1ZDcApPN3dkMHRySGwwSW5TbEtsejFLeVlHd1NBRXlzejVVMDBCdTdWbHc1RXpqVFZqYThXK3p6N0Uza04raG1kb1U5CkdsNzU3Nk5Bdms3NHhPY3JmaXh4NTVqZnl1Um93QnltbExaZXlTdWR3Q3drbU52R2ZxSm5lS296RzZOQnhEdy8KMG5kUnlEOENnZ0VCQUxKK2ZaeWZha0t6WUVJYXk5QnJMeWE2RVVCamxHbC93NDRRb3FIOG9hdTNvTlkxYytpSgpRcXZqRG1qemZYVHNFQTBsTEFGNldTWnFON3ZDeGdadDdLYWlpNWd0b2hxUXpMU3B0a0s4SGxacjNmaDUyMDNlCkF6aGNrZ2EwUWNUWmNneG9Fek1QWEs3Z21nVWIrSHhGZFFCcTQ0RUpCV3hlNy9HeUhFV2NUT2pzREIvTUxGNTYKN1VOSWsyK0dGb21mQWYyTG5FUDVZS2VlYW5nRUZhSDcwdE14cWtwbnJENWJjQ3J1a3oyNUNoOW9LZlg3K3liQwozKzdlMzZ2bUpqc0xPbUdIWDFUV3pJREdBUUg5aHZGTXhtUEZFalBFMGcycmY0OWoyWGVqdHJNaG5FOUpFTXBaCjQxTDA1SEY4NXdtcXZucERqVTg4OHMzR1JXeGZxTzViS2JrQ2dnRUFLU1h4STRmV3Z6MzFIQTBkNzQ3a25lOWQKQ0JCSys3aC8wZVBqR3JOOTVjd3ZCL3NNSHZNd0pyQVN1b2YvblFxbll6ZEp4b1NaanhUZFRseXhHekJ3ZWVXQQpuenZ0K0Y5aWhaOUlkMEhPd2RnMldneDFrd09FNGRoWUQxc3pSMm8yRFVIRkVLOFVVcDdvSjhqWGFYejJ3OGZxCjhWOU9EMW51RHRPcFZIcnJEQ2RmNFBMYVNPb1lCT3BkR09uTkd4SVJ2cHBha2JFSEZWOEM4T3RVTDFoK1BlZTEKeWxPZDZvTmV1YzI4alRoaGdZaVBjYW5YbWhRSTNuVWRqVlpuZFNmR2E4WlRmWmpnSlQ0MEdxMDZIREpJNms4ZQp0SFpJZTc2Ull1NXlwK1ptczFKaWROampueGtPb0VJZyttMnFWcWxvWmZJYWNCVlgyNUMxdk9jbVFGLzJOdz09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg"
  publicKey: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUF1eHZoazIwcWxFWnNwbHF3RlB3dAorSTNaTW5neURhSVhXSEZoajRzTEdPQXhpcS9BcmJCc3NoWmwzcUJHdGdDa0RwK3U0eUNUT1VYUExvTmNWZDA2ClVaYVFKdTJOWTc5TkhDejF2UlBYRE11bmI1RUNPdkxnK2x2R3lMaWF6eW1yM0ZEWXRYMWZjQm9MVkJUUlZNS2wKYmFlK3VDcFhMSDdBYW42SlkyaFU3NWtXZndnRTdXYWtLQTV2OGc2MGtLUE0zRDFoM2hVY2NOcll5SzcxNEx3MAppMjZhbkZGRHl6TDBSbVNrL21paThSMGtsZUx2WTVrOGhTaHMxcGRSejFqWmlPbVluV0I1QXJ5Mm1WRzJ5dVF3ClQxQ3IxNUYvRFh2UUdVZ2d6MXNnODNucFJpaGdNc3NxSlZZYjJ4UlVid2R5b1RodUNGdEF2Y3NqTm5LWHU4b0EKVXZtVFprZ3BGdXZ2aVBOK0E4RmV6Zk5Obk1BUk5WbU1uTGN1WUdqdmU5dXN2NWVnT2Z6VHJkUjlCMEp3YUpjRwpmOEc0V09IRGVlb1lZNnFpVnU2dWJBQXJSYVhJUlVBVUo4cTBRQXBRVk1sVmVwNFdCK0ZQVUVUV3IvSDBQWnNTCkdYdjZhdFdWWk04WTRLajQ4NUZ2MTZTSVU5elpadGJJSGNXZzNseUIwdGlVSFNKRlBHdkxvM3VjTlM5UHlCR1QKYUV3RDE1NkkzeDgrZmdBZnRnY2pwcUZpbFFqVmFJcFpjVEFYNnVoOVBaMWIvT0NsNVJ2c1AyMEFVS3dSdDRHNwppanNZNlZ3dGk2cXBEemF3ZmthYklSN3NpalZ3VWNGWVVTYWRpWmNTbHRIbnZTU1BHU29NTjg5S1laVXZZeXV0CmhWRVExL2tTeFA5aDRxbWl6YkVXSWtNQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo="
  secret: ""
  jwt:
    id:
    privateKey:
  dependencies:
    arc:
      apikey: 8b55691f-346d-423c-bdcf-3f5365806d39
      auth: apikey
      location: https://taalhuizen-bisc.commonground.nu/api/v1/arc
    bs:
      apikey: 8b55691f-346d-423c-bdcf-3f5365806d39
      auth: apikey
      location: https://taalhuizen-bisc.commonground.nu/api/v1/bs
    chrc:
      apikey: 8b55691f-346d-423c-bdcf-3f5365806d39
      auth: apikey
      location: https://taalhuizen-bisc.commonground.nu/api/v1/chrc
    cmc:
      apikey: 8b55691f-346d-423c-bdcf-3f5365806d39
      auth: apikey
      location: https://taalhuizen-bisc.commonground.nu/api/v1/cmc
    cc:
      apikey: 8b55691f-346d-423c-bdcf-3f5365806d39
      auth: apikey
      location: https://taalhuizen-bisc.commonground.nu/api/v1/cc
    eav:
      apikey: 8b55691f-346d-423c-bdcf-3f5365806d39
      auth: apikey
      location: https://taalhuizen-bisc.commonground.nu/api/v1/eav
    edu:
      apikey: 8b55691f-346d-423c-bdcf-3f5365806d39
      auth: apikey
      location: https://taalhuizen-bisc.commonground.nu/api/v1/edu
    mrc:
      apikey: 8b55691f-346d-423c-bdcf-3f5365806d39
      auth: apikey
      location: https://taalhuizen-bisc.commonground.nu/api/v1/mrc
    memo:
      apikey: 8b55691f-346d-423c-bdcf-3f5365806d39
      auth: apikey
      location: https://taalhuizen-bisc.commonground.nu/api/v1/memo
    rc:
      apikey: 8b55691f-346d-423c-bdcf-3f5365806d39
      auth: apikey
      location: https://taalhuizen-bisc.commonground.nu/api/v1/rc
    uc:
      apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      auth: apikey
      location: https://taalhuizen-bisc.commonground.nu/api/v2/user-component
    wrc:
      apikey: 8b55691f-346d-423c-bdcf-3f5365806d39
      auth: apikey
      location: https://taalhuizen-bisc.commonground.nu/api/v1/wrc

php:
  repository: docker.io/conduction/protocomponent-php
  image: ghcr.io/conductionnl/taalhuizen-service-php
  tag: latest
  env: prod
  replicaCount: 2
  pullPolicy: Always
  trustedHosts: '^.+$'
  corsAllowOrigin: ['*']
  trustedProxies:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16

redis:
  cluster:
    enabled: false
  redisPort: 6379
  usePassword: false
  enabled: false
  pullPolicy: IfNotPresent

nginx:
  repository: docker.io/conduction/protocomponent-nginx
  image: ghcr.io/conductionnl/taalhuizen-service-nginx
  tag: latest
  pullPolicy: Always
  replicaCount: 2

postgresql:
  enabled: true
  imageTag: 10-alpine
  # If bringing your own PostgreSQL, the full uri to use
  url: "psql://a:b@example.com/c"
  postgresqlUsername: "example"
  postgresqlPassword: "!ChangeMe!"
  postgresqlDatabase: "api"
  # Persistent Volume Storage configuration.
  # ref: https://kubernetes.io/docs/user-guide/persistent-volumes
  persistence:
    enabled: true
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  type: "nginx"
  hostname: taalhuizen-service.local
  path: /
  annotations:
    # kubernetes.io/ingress.global-static-ip-name: chart-ip
    # kubernetes.io/ingress.class: gce
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace, you can also use cert-manager.
    # - hosts:
    # - example.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
