apiVersion: v1
kind: Secret
metadata:
    name: {{ template "fullname" . }}-dependencies
    labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/part-of: {{ .Release.Name }}
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
    dependencies.yaml: |
        parameters:
            {{- if and .Values.security.jwt.id .Values.security.jwt.privateKey }}
            jwt:
                id: {{ .Values.security.jwt.id | quote }}
                privateKey: {{ .Values.security.jwt.privateKey | quote }}
            {{- end }}

            {{- if .Values.security.dependencies }}
            components:
{{ .Values.security.dependencies | toYaml | indent 16 }}
  {{- end }}
