{{- $postgresqlServiceName := include "postgresql.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.settings.name }}
    app.kubernetes.io/part-of: {{ .Values.settings.name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://%s:%s@%s/%s?serverVersion=10" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword $postgresqlServiceName .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  {{ else }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{ end }}
  app_application_key: {{ .Values.security.applicationKey | b64enc | quote }}
